// Generated by scripts/sync-skin-catalog.mjs. Do not edit manually.
import type { Skin } from '../domain/types';

export const skinCatalog = [
  {
    "id": "8c72ae0b-4357-1a75-ad62-fbaec7b64f92",
    "name": "2022全球冠军赛 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "InspectAndKill",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/8c72ae0b-4357-1a75-ad62-fbaec7b64f92/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/0d81cec6-46a2-300f-c3c6-7aa67c2b8547/fullrender.png"
  },
  {
    "id": "cc1da8cd-452f-a007-0bf8-b68a471c3a6e",
    "name": "2024全球冠军赛 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "InspectAndKill",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/cc1da8cd-452f-a007-0bf8-b68a471c3a6e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/3e4ff383-493d-4f52-ba0b-6a9df9e6bef8/fullrender.png"
  },
  {
    "id": "9877d50b-43b1-837a-802a-bf8a3b98e2dd",
    "name": "781-A协议 幻影",
    "weapon": "phantom",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "VFX",
      "Animation",
      "Finisher",
      "Voiceover"
    ],
    "image": "https://media.valorant-api.com/weaponskins/9877d50b-43b1-837a-802a-bf8a3b98e2dd/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/89f9432f-4c8e-cefe-73bd-26966c875647/fullrender.png"
  },
  {
    "id": "02ed7299-4035-c973-4a26-9f8c6d454e63",
    "name": "暗域界碑 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/02ed7299-4035-c973-4a26-9f8c6d454e63/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/566c1ead-4185-05ac-62be-02ad8b42ce8c/fullrender.png"
  },
  {
    "id": "320c4baa-41e8-ac8f-91eb-0fbc7bf3c145",
    "name": "黯夜怪谈 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/320c4baa-41e8-ac8f-91eb-0fbc7bf3c145/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/15470687-4c9b-62c5-6a74-7f9f34e4e8a0/fullrender.png"
  },
  {
    "id": "36791b03-452d-8dad-0091-898cc28d2196",
    "name": "般若假面 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/36791b03-452d-8dad-0091-898cc28d2196/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6096a66f-43d2-d4ad-6421-84aee3386921/fullrender.png"
  },
  {
    "id": "980fa063-436e-e51f-c38d-70a5b93a0f1c",
    "name": "电音光谱 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/980fa063-436e-e51f-c38d-70a5b93a0f1c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/e9014a77-4a74-4ea7-999c-44b0d0f84daa/fullrender.png"
  },
  {
    "id": "7ae63121-4cf0-b4db-00ed-eb8ef05572b1",
    "name": "盖亚的复仇//2.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/7ae63121-4cf0-b4db-00ed-eb8ef05572b1/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/c48c2bad-4bbb-cb8c-6400-5c9a3942077e/fullrender.png"
  },
  {
    "id": "a8652d02-458c-461c-8aa8-b7a520455023",
    "name": "光明哨兵//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/a8652d02-458c-461c-8aa8-b7a520455023/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/271066c7-4cc5-9530-b696-bd89c12c97ee/fullrender.png"
  },
  {
    "id": "1cb0bdf7-46e1-92d5-b400-988c99f25d81",
    "name": "归零者//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/1cb0bdf7-46e1-92d5-b400-988c99f25d81/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/38655ca2-49a3-1b90-a555-62bbacb09ffa/fullrender.png"
  },
  {
    "id": "516ff0cb-4d4b-bf0e-d460-92b3c8d27259",
    "name": "海洋之星//2.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/516ff0cb-4d4b-bf0e-d460-92b3c8d27259/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/55569f42-4a74-0aaa-4538-598ce3063c10/fullrender.png"
  },
  {
    "id": "34560475-4eaa-d2be-b37f-908463413482",
    "name": "洪荒怒焰 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/34560475-4eaa-d2be-b37f-908463413482/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/dcaa8ecd-489d-27e3-4953-19b7e9d00622/fullrender.png"
  },
  {
    "id": "26094344-4ac4-6656-763a-d2b338fea14a",
    "name": "毁灭骑士 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/26094344-4ac4-6656-763a-d2b338fea14a/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/70f7c098-476b-8867-743f-04996427e51a/fullrender.png"
  },
  {
    "id": "ad2c5365-4147-23da-afaa-08b9bfb3817b",
    "name": "混沌序曲//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/ad2c5365-4147-23da-afaa-08b9bfb3817b/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/8b132ed4-46b8-84e0-e0ec-caa69d1818ea/fullrender.png"
  },
  {
    "id": "e86bf7e4-4dd3-fbee-533b-fa875344bbaf",
    "name": "离子武器 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/e86bf7e4-4dd3-fbee-533b-fa875344bbaf/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/b9c9eb56-4cbd-04b7-06a8-329dc6f1e73a/fullrender.png"
  },
  {
    "id": "c1b96274-4346-2ea4-65f4-ec957d217922",
    "name": "胧夜月华 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/c1b96274-4346-2ea4-65f4-ec957d217922/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/58b05ae6-4126-2be4-84c1-1e9d63409091/fullrender.png"
  },
  {
    "id": "044b28ba-4c3b-d315-140d-d9a249da5567",
    "name": "掠影//2.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/044b28ba-4c3b-d315-140d-d9a249da5567/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/444ee547-4a4a-8202-685f-50b15113a77f/fullrender.png"
  },
  {
    "id": "2b89c4cc-4517-c2db-a08f-c484f0f614d7",
    "name": "末日泡泡 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2b89c4cc-4517-c2db-a08f-c484f0f614d7/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/c948bb3b-4253-6597-d39e-e6bedf0a988a/fullrender.png"
  },
  {
    "id": "59af9c5d-43ee-1360-f3a7-a9a6ff6e478b",
    "name": "砰砰X特攻队 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/59af9c5d-43ee-1360-f3a7-a9a6ff6e478b/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/0c6f30f3-4ed4-b113-6aaa-139e218f9dc6/fullrender.png"
  },
  {
    "id": "5b43d27b-419c-f2bc-53fe-d7829dad46b3",
    "name": "破败军械 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/5b43d27b-419c-f2bc-53fe-d7829dad46b3/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/0d6eac16-4f0f-1014-e6b2-65aa72f2edff/fullrender.png"
  },
  {
    "id": "5eec4ce6-443d-e9b5-4c5b-2b967d426bd3",
    "name": "奇点 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/5eec4ce6-443d-e9b5-4c5b-2b967d426bd3/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/36d14ec2-4376-a355-ad98-bdbc9b4b9e9a/fullrender.png"
  },
  {
    "id": "f2531d6f-40d8-ad18-4e74-ed812e0a6b1f",
    "name": "奇幻朋克//3.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/f2531d6f-40d8-ad18-4e74-ed812e0a6b1f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/0f3ac4e7-4723-6069-4875-f89c32db7894/fullrender.png"
  },
  {
    "id": "ce85f078-474a-eae4-3844-03a49625df15",
    "name": "千灵华绽 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/ce85f078-474a-eae4-3844-03a49625df15/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/4cd0c608-4ce4-d8fa-bc3d-0db56ec1c897/fullrender.png"
  },
  {
    "id": "25a7f0f2-4bce-7e45-b4b0-ca9264f5dfcc",
    "name": "全息波普//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/25a7f0f2-4bce-7e45-b4b0-ca9264f5dfcc/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/7dd3f7d8-455b-bc3a-94b8-af9fba0bebed/fullrender.png"
  },
  {
    "id": "64c97d19-4142-ce97-7a13-53a5b1ebdc82",
    "name": "神中神罚 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/64c97d19-4142-ce97-7a13-53a5b1ebdc82/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/561f89c8-4478-5212-1dc4-d793b5de62ce/fullrender.png"
  },
  {
    "id": "3f6410af-4fd7-74fb-c0f4-6ab61d30022c",
    "name": "塑水宗//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/3f6410af-4fd7-74fb-c0f4-6ab61d30022c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/cb1ad7ed-4f7d-3708-08db-6e9137ba4ca8/fullrender.png"
  },
  {
    "id": "42fe7bf8-40ba-b1f4-df5e-34a6f51f29bf",
    "name": "天界神兵//2.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/42fe7bf8-40ba-b1f4-df5e-34a6f51f29bf/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/afdf5cf0-4af4-579c-3e59-d2b99904e99c/fullrender.png"
  },
  {
    "id": "52417dc8-48b7-111a-b63b-5db108b2e63a",
    "name": "西部未来 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "Animation",
      "Transformation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/52417dc8-48b7-111a-b63b-5db108b2e63a/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/9663ea87-4ff9-2934-0919-1fb72ee59a9b/fullrender.png"
  },
  {
    "id": "2aac8bb3-4cfa-b806-21e4-5a8e9904caa4",
    "name": "虚空遗器 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2aac8bb3-4cfa-b806-21e4-5a8e9904caa4/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6a203339-4efb-55fd-3473-b59503c224b2/fullrender.png"
  },
  {
    "id": "fe7cd972-4651-2865-257b-51846321ad61",
    "name": "异鳞魔蛇 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/fe7cd972-4651-2865-257b-51846321ad61/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/08fdca4f-44a3-ffe9-63ef-e0ab6e98dcfb/fullrender.png"
  },
  {
    "id": "2371d9e1-498c-1ad1-4f10-d1a339c7fda2",
    "name": "源能者危机001 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2371d9e1-498c-1ad1-4f10-d1a339c7fda2/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/0bddb2dc-44c0-a476-ca06-629b1f110515/fullrender.png"
  },
  {
    "id": "4eb45d71-4fa4-be4f-7409-cf92123f1d22",
    "name": "源能者娱乐系统 幻影",
    "weapon": "phantom",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/4eb45d71-4fa4-be4f-7409-cf92123f1d22/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/4f04a759-4406-9ab7-18b4-0a9044ecdd60/fullrender.png"
  },
  {
    "id": "d67b929f-4431-61c0-286e-3ebf3d11c4af",
    "name": "侦察力量 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "Randomizer",
      "KillBanner"
    ],
    "image": "https://media.valorant-api.com/weaponskins/d67b929f-4431-61c0-286e-3ebf3d11c4af/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/273edf84-45cf-0266-21d8-a4969bd31b6d/fullrender.png"
  },
  {
    "id": "44b7b110-46bf-ccbb-2613-29a5df296461",
    "name": "紫阙金琅//2.0 幻影",
    "weapon": "phantom",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/44b7b110-46bf-ccbb-2613-29a5df296461/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/264eaaeb-4038-4bf4-3760-eb9f9c21edcb/fullrender.png"
  },
  {
    "id": "7581e975-418f-fe4f-e3b0-08a3000e9a8d",
    "name": "ORA x 颗秒 幻影",
    "weapon": "phantom",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher",
      "SongShuffle"
    ],
    "image": "https://media.valorant-api.com/weaponskins/7581e975-418f-fe4f-e3b0-08a3000e9a8d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/75ab3a8e-471c-00c7-5e38-37ad5e1bff6a/fullrender.png"
  },
  {
    "id": "499acf05-4f79-e345-3714-57bf7aa163ea",
    "name": "RGX 11z Pro//2.0 幻影",
    "weapon": "phantom",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher",
      "KillCounter"
    ],
    "image": "https://media.valorant-api.com/weaponskins/499acf05-4f79-e345-3714-57bf7aa163ea/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/1788506c-4cd4-5a85-12cc-288b566ed869/fullrender.png"
  },
  {
    "id": "84589da8-4e2b-11bf-ca52-b88e6b7e1dbd",
    "name": "781-A协议 正义",
    "weapon": "sheriff",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "VFX",
      "Animation",
      "Finisher",
      "Voiceover"
    ],
    "image": "https://media.valorant-api.com/weaponskins/84589da8-4e2b-11bf-ca52-b88e6b7e1dbd/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/dd1d4ad8-4672-2d69-6530-03bf7b308d58/fullrender.png"
  },
  {
    "id": "8504529f-4555-64a6-6f18-28a4438336e1",
    "name": "暗域界碑 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/8504529f-4555-64a6-6f18-28a4438336e1/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/869d9325-4712-5e62-afc4-15843ad56b76/fullrender.png"
  },
  {
    "id": "2109efb1-432f-8fe8-897b-31a9d135ac3c",
    "name": "创·纪元 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2109efb1-432f-8fe8-897b-31a9d135ac3c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/a9489e1e-41e6-df6d-897f-fc8943a556e7/fullrender.png"
  },
  {
    "id": "2ba3ded8-47d5-58e3-1307-39800214636d",
    "name": "光明哨兵 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2ba3ded8-47d5-58e3-1307-39800214636d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/feab1ba7-4695-f052-7563-a380eb896784/fullrender.png"
  },
  {
    "id": "317574ca-4a9d-9e5a-f9c4-a79aa378f75b",
    "name": "归零者//2.0 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/317574ca-4a9d-9e5a-f9c4-a79aa378f75b/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/262d6e2f-4878-bf05-37d6-339fd7d969d1/fullrender.png"
  },
  {
    "id": "42e25a14-4ef6-19ef-d013-6db2afcb44c3",
    "name": "毁灭骑士 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/42e25a14-4ef6-19ef-d013-6db2afcb44c3/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/1c4aaf2c-4e6e-fc7e-a696-0f89a92202f4/fullrender.png"
  },
  {
    "id": "81bd181f-4124-9e58-ffd4-09964dc0d2cc",
    "name": "混沌序曲//2.0 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/81bd181f-4124-9e58-ffd4-09964dc0d2cc/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/463fe130-4b39-c71b-9df5-d2b777d71633/fullrender.png"
  },
  {
    "id": "208bdc02-451d-60e5-196c-47ae67f150fc",
    "name": "机动狂飙 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/208bdc02-451d-60e5-196c-47ae67f150fc/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/2dfe5557-411f-a182-68b8-5a98d2d42c27/fullrender.png"
  },
  {
    "id": "83778c03-45a3-67a2-3c89-6b8598327d58",
    "name": "离子武器 正义",
    "weapon": "sheriff",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/83778c03-45a3-67a2-3c89-6b8598327d58/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/d3f81911-44e7-f0c1-cc6c-34bda3bff6d3/fullrender.png"
  },
  {
    "id": "a40a6ce2-462c-c864-5d30-7b9408b98d3d",
    "name": "掠影 正义",
    "weapon": "sheriff",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/a40a6ce2-462c-c864-5d30-7b9408b98d3d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/c092687f-4af4-f843-f68b-b989000e240d/fullrender.png"
  },
  {
    "id": "c7049e63-4c65-dd0e-20ec-7c956217e894",
    "name": "末日泡泡 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/c7049e63-4c65-dd0e-20ec-7c956217e894/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/be746028-4281-14a7-f58f-abb439ea225d/fullrender.png"
  },
  {
    "id": "bfd9e773-4376-1f6a-98f2-dc93f0c0607c",
    "name": "奇点 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/bfd9e773-4376-1f6a-98f2-dc93f0c0607c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/00831706-4e60-d5f9-b600-e38be89828d0/fullrender.png"
  },
  {
    "id": "6460edbf-458d-bf61-7519-519305ba5da2",
    "name": "奇幻朋克//2.0 正义",
    "weapon": "sheriff",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/6460edbf-458d-bf61-7519-519305ba5da2/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/2f82f035-47c9-e040-fb43-77a67ee408d9/fullrender.png"
  },
  {
    "id": "c0a39e8b-4d52-bfbc-21f2-a88b0f8c4856",
    "name": "千灵华绽 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/c0a39e8b-4d52-bfbc-21f2-a88b0f8c4856/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/d5f4a19d-4383-117c-9756-b39a8383bad2/fullrender.png"
  },
  {
    "id": "db41461d-4cee-b397-09ff-f2b0d8f012f4",
    "name": "日冕雄师 正义",
    "weapon": "sheriff",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/db41461d-4cee-b397-09ff-f2b0d8f012f4/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/354d1f47-4244-3f3a-fb96-afbe54cd08c1/fullrender.png"
  },
  {
    "id": "84d840c5-4479-4395-d823-e7acbe634c5e",
    "name": "双城之战 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX"
    ],
    "image": "https://media.valorant-api.com/weaponskins/84d840c5-4479-4395-d823-e7acbe634c5e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/e93656e2-42f9-8eb1-8b74-e5829f3eb08e/fullrender.png"
  },
  {
    "id": "0eec6f2b-4d64-9c16-7846-b8865030f61c",
    "name": "塑水宗 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/0eec6f2b-4d64-9c16-7846-b8865030f61c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/8ee58b76-435a-8dcc-216a-059f1b7f828c/fullrender.png"
  },
  {
    "id": "b73f455a-4d77-44e7-fd90-1db9db82a8f6",
    "name": "西部未来 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "Animation",
      "Transformation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/b73f455a-4d77-44e7-fd90-1db9db82a8f6/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6c75e3ae-4500-a127-b0ab-349cd9583539/fullrender.png"
  },
  {
    "id": "97a3cdc4-4f3a-ed26-02d6-6dbf6c1380d0",
    "name": "猩红猛兽 正义",
    "weapon": "sheriff",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "KillEffect"
    ],
    "image": "https://media.valorant-api.com/weaponskins/97a3cdc4-4f3a-ed26-02d6-6dbf6c1380d0/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6c78d9d4-4955-1044-f7e9-b4bd2c7b4dbd/fullrender.png"
  },
  {
    "id": "e1fdd246-4a6c-af26-f0a0-65a48f2586da",
    "name": "虚空遗器 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/e1fdd246-4a6c-af26-f0a0-65a48f2586da/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/30d62003-49f2-9ef8-8393-6aa94893c18d/fullrender.png"
  },
  {
    "id": "9eba83e5-4084-300e-d001-fd8152dc6522",
    "name": "偃月苍龙 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/9eba83e5-4084-300e-d001-fd8152dc6522/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/78793f1f-4ac6-2441-e46c-58a56366de58/fullrender.png"
  },
  {
    "id": "5ff60bfc-4a7f-b9bf-245d-f2b4e31de6a4",
    "name": "银河子午线 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/5ff60bfc-4a7f-b9bf-245d-f2b4e31de6a4/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/15cfe9f1-4eb1-8b21-9cf0-67bd31062802/fullrender.png"
  },
  {
    "id": "a452fcd9-4fe6-dc8c-6459-b2ad13ef89ff",
    "name": "ORA x 颗秒 正义",
    "weapon": "sheriff",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher",
      "SongShuffle"
    ],
    "image": "https://media.valorant-api.com/weaponskins/a452fcd9-4fe6-dc8c-6459-b2ad13ef89ff/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/5b9779b4-48cc-e53c-4043-3681c7067ddb/fullrender.png"
  },
  {
    "id": "142be691-42a0-c0a1-f6ed-57b3158def7e",
    "name": "RGX 11z Pro//3.0 正义",
    "weapon": "sheriff",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher",
      "KillCounter"
    ],
    "image": "https://media.valorant-api.com/weaponskins/142be691-42a0-c0a1-f6ed-57b3158def7e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/e81ce00c-49ea-b33d-693e-00a212c9d67d/fullrender.png"
  },
  {
    "id": "9bf19b77-4b33-7203-9f2c-16932970622f",
    "name": "2021全球冠军赛 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "InspectAndKill",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/9bf19b77-4b33-7203-9f2c-16932970622f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/140a48ad-4daf-a6f8-027c-a5b890eac738/fullrender.png"
  },
  {
    "id": "b0f65660-4c51-13b7-9d01-e29a1e2879b0",
    "name": "2023全球冠军赛 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "InspectAndKill",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/b0f65660-4c51-13b7-9d01-e29a1e2879b0/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/681caac1-4a61-999a-6880-e3a9ed6acf6d/fullrender.png"
  },
  {
    "id": "15cc1aab-432f-34d8-e0e8-d2925d54324b",
    "name": "2025全球冠军赛 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "InspectAndKill"
    ],
    "image": "https://media.valorant-api.com/weaponskins/15cc1aab-432f-34d8-e0e8-d2925d54324b/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/e986283f-493a-0777-41d8-c49b47052472/fullrender.png"
  },
  {
    "id": "4f5ee03a-4204-5526-6941-bca4f911a768",
    "name": "艾沃莉的梦之翼 狂徒",
    "weapon": "vandal",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": null,
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/1bf0d77f-4e94-9dc0-7a7a-fb8430b569d3/fullrender.png"
  },
  {
    "id": "7156c2ee-41fc-f8f4-d457-ebb287965c08",
    "name": "般若假面//2.0 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/7156c2ee-41fc-f8f4-d457-ebb287965c08/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/7bd85530-4a2a-a463-733c-47a4daac3e91/fullrender.png"
  },
  {
    "id": "f328add7-4710-ab8d-95bb-409bc8278a35",
    "name": "冰点凝冻 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/f328add7-4710-ab8d-95bb-409bc8278a35/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/886d24da-42ba-62cd-9d25-a7813ee686cc/fullrender.png"
  },
  {
    "id": "b8a6d8f5-4171-c0f3-eab4-9bb64af25f4f",
    "name": "超时空卫队 狂徒",
    "weapon": "vandal",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/b8a6d8f5-4171-c0f3-eab4-9bb64af25f4f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/1f8aaf7a-4f41-c8c2-9d7d-1ba3cf469e70/fullrender.png"
  },
  {
    "id": "6d0e7907-45e1-ca59-3bd4-66a454963957",
    "name": "赤焰铁骥 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/6d0e7907-45e1-ca59-3bd4-66a454963957/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/7aa05464-4cd1-8143-58a7-df8d354793a5/fullrender.png"
  },
  {
    "id": "59032dea-4759-1768-74c9-3796a69a0e32",
    "name": "创·纪元 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/59032dea-4759-1768-74c9-3796a69a0e32/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/77216b46-4fa8-b84c-e580-7c8ee9b37525/fullrender.png"
  },
  {
    "id": "3a079e06-4b63-2293-fbd8-4fb896e8af3d",
    "name": "多弥尔的复仇 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/3a079e06-4b63-2293-fbd8-4fb896e8af3d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/f3a01eb6-405b-70de-4f5e-5eb2ced246a9/fullrender.png"
  },
  {
    "id": "437307c6-424c-6a48-9738-949b91166353",
    "name": "堕天遗武 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/437307c6-424c-6a48-9738-949b91166353/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6273d900-47de-65bb-29c9-ea934faadfef/fullrender.png"
  },
  {
    "id": "c2c7746c-496a-6372-bd7a-3186276db2d1",
    "name": "盖世英雄 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/c2c7746c-496a-6372-bd7a-3186276db2d1/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/a833b92c-4981-6d12-191d-25b85f5d8bd5/fullrender.png"
  },
  {
    "id": "000ad7b1-44b0-9345-ea47-9cbd7dcdbb38",
    "name": "盖亚的复仇 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/000ad7b1-44b0-9345-ea47-9cbd7dcdbb38/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/c9d93000-4133-3f68-20ea-81a307ef0540/fullrender.png"
  },
  {
    "id": "e8df3725-40de-b8ec-77bd-62a989685a85",
    "name": "光明哨兵 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/e8df3725-40de-b8ec-77bd-62a989685a85/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/6f337971-40b7-c94d-0f24-36869af654c6/fullrender.png"
  },
  {
    "id": "5a510a45-4b2a-2b9a-bd78-1ea6d229ba38",
    "name": "光荣异象 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Transformation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/5a510a45-4b2a-2b9a-bd78-1ea6d229ba38/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/eeace112-4611-db5c-d784-d9bd0797ff3c/fullrender.png"
  },
  {
    "id": "4c926aa9-4f26-bc80-c486-9b888333373f",
    "name": "归零者 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/4c926aa9-4f26-bc80-c486-9b888333373f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/a09f9850-4cb9-d0aa-63c7-6dbb5a64f27e/fullrender.png"
  },
  {
    "id": "db91451c-4309-2c8c-eded-bf842d844e52",
    "name": "海洋之星 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "FishAnimation",
      "KillBanner"
    ],
    "image": "https://media.valorant-api.com/weaponskins/db91451c-4309-2c8c-eded-bf842d844e52/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/9a2125b3-4e53-4757-fe1c-4e9b31ae0c28/fullrender.png"
  },
  {
    "id": "a70fd508-44ea-8de3-3b30-d3a7eb9db42e",
    "name": "洪荒怒焰 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/a70fd508-44ea-8de3-3b30-d3a7eb9db42e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/12702ab7-4194-2ec1-ff26-6084b0c640fc/fullrender.png"
  },
  {
    "id": "522a264e-4ca7-adb0-6cf1-28b2ef938727",
    "name": "混沌序曲 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/522a264e-4ca7-adb0-6cf1-28b2ef938727/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/10ff3757-4099-f828-d391-e28d2e634924/fullrender.png"
  },
  {
    "id": "bbd3a52f-411e-3475-a6aa-ea88b54de53c",
    "name": "机动狂飙 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/bbd3a52f-411e-3475-a6aa-ea88b54de53c/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/048ab630-4117-a932-d26d-208aad284072/fullrender.png"
  },
  {
    "id": "4f1823dd-4a17-7511-6ac8-4aa28a6a263a",
    "name": "荆刺圣骸 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/4f1823dd-4a17-7511-6ac8-4aa28a6a263a/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/75ea21d8-453d-ef05-47d4-948bf221bdae/fullrender.png"
  },
  {
    "id": "596ce51d-40e3-dc21-b02d-b08d070a7883",
    "name": "离子武器//2.0 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/596ce51d-40e3-dc21-b02d-b08d070a7883/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/22ec09d9-4b0f-c9a4-e843-db8d6af8d110/fullrender.png"
  },
  {
    "id": "30388628-42f0-606c-82c0-73ad43de997f",
    "name": "掠影 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/30388628-42f0-606c-82c0-73ad43de997f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/2bd28382-48c6-8579-83e8-e9b64b783de3/fullrender.png"
  },
  {
    "id": "1b9b0131-42fe-b6a7-d212-699b342ba642",
    "name": "逆命中队 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/1b9b0131-42fe-b6a7-d212-699b342ba642/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/b2a27b8b-41d2-af46-50a2-b1a3abb42c76/fullrender.png"
  },
  {
    "id": "d6c7ff28-467e-bb3f-3c0c-c5b9445e55ca",
    "name": "奇点//2.0 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/d6c7ff28-467e-bb3f-3c0c-c5b9445e55ca/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/ddad90bf-4333-5f7a-4c33-8b8185d03922/fullrender.png"
  },
  {
    "id": "148d7f02-4259-9c17-a1a4-6fa220a56551",
    "name": "奇幻朋克//3.0 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/148d7f02-4259-9c17-a1a4-6fa220a56551/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/71c769ce-48d7-fe22-2d4b-a996afd0a076/fullrender.png"
  },
  {
    "id": "6c4315b8-4ff1-baaa-5aac-5790c7443353",
    "name": "起源 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/6c4315b8-4ff1-baaa-5aac-5790c7443353/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/de2a2b29-4a65-459e-a822-ccacbff53d46/fullrender.png"
  },
  {
    "id": "4fc36214-4492-ef57-f8fb-4cab81863545",
    "name": "千灵华绽//2.0 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/4fc36214-4492-ef57-f8fb-4cab81863545/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/087f02e8-4676-b272-2a16-f6bdd3612a45/fullrender.png"
  },
  {
    "id": "74789f33-4632-8052-96d7-258538721a32",
    "name": "全息波普//2.0 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/74789f33-4632-8052-96d7-258538721a32/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/b58f249b-4e8f-5532-6f35-a9b3b39dc15c/fullrender.png"
  },
  {
    "id": "1df79598-42a0-a433-0aa5-c79047c32779",
    "name": "日冕雄师 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/1df79598-42a0-a433-0aa5-c79047c32779/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/c3b9eeee-4528-5f40-db92-5281f66ce397/fullrender.png"
  },
  {
    "id": "18609205-4edb-5966-cff8-0fba0230ba1e",
    "name": "上古龙炎 狂徒",
    "weapon": "vandal",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/18609205-4edb-5966-cff8-0fba0230ba1e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/835ad8e3-4b0e-071b-ce38-00a05032ac43/fullrender.png"
  },
  {
    "id": "e06fd704-4171-b5ea-5028-d3befb62107d",
    "name": "噬影者 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/e06fd704-4171-b5ea-5028-d3befb62107d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/1cf7b70a-4555-82b2-e2ee-25beb3e33fa1/fullrender.png"
  },
  {
    "id": "4ccb9517-4762-eb45-1242-7ca667223459",
    "name": "双城之战 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/4ccb9517-4762-eb45-1242-7ca667223459/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/e9b5e915-4113-92f6-2ec2-febdf2763f5a/fullrender.png"
  },
  {
    "id": "d8d5d7a1-4d81-8560-54bc-0692ab40f69b",
    "name": "塑水宗 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/d8d5d7a1-4d81-8560-54bc-0692ab40f69b/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/3637a0be-4785-8841-9893-1198325185f2/fullrender.png"
  },
  {
    "id": "8e762a1f-4102-b7ce-d6a0-9690c5bfe160",
    "name": "虚空遗器 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/8e762a1f-4102-b7ce-d6a0-9690c5bfe160/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/d6be385b-44f7-271a-6b1b-34be3251b6c7/fullrender.png"
  },
  {
    "id": "917ca6e8-403e-3691-78d9-a8aa6118385f",
    "name": "偃月苍龙 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "VFX",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/917ca6e8-403e-3691-78d9-a8aa6118385f/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/45ae6708-4dd0-4d01-3a5c-eab3764a5807/fullrender.png"
  },
  {
    "id": "b6f79657-4a6d-e2ae-3d64-4fbcde2958a4",
    "name": "耀鳞威龙 狂徒 ",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/b6f79657-4a6d-e2ae-3d64-4fbcde2958a4/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/301fef53-4091-7bf8-07b9-bc8701b217a5/fullrender.png"
  },
  {
    "id": "7c4f7e27-4dcb-0b66-659f-cc94d720e67e",
    "name": "银河子午线 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/7c4f7e27-4dcb-0b66-659f-cc94d720e67e/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/aa6c599d-42a6-326d-5c4a-3895308ddfb6/fullrender.png"
  },
  {
    "id": "caf8d2e7-4763-b990-4f2e-59b551d7576d",
    "name": "滋滋X特攻队 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/caf8d2e7-4763-b990-4f2e-59b551d7576d/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/fb9b07eb-4591-d22c-a611-bb821664fbf6/fullrender.png"
  },
  {
    "id": "b9ee2457-481c-6776-3f5b-0ca8e8f90c89",
    "name": "紫阙金琅 狂徒",
    "weapon": "vandal",
    "tier": "卓越",
    "tierRank": 2,
    "effects": [
      "VFX",
      "Animation",
      "Finisher"
    ],
    "image": "https://media.valorant-api.com/weaponskins/b9ee2457-481c-6776-3f5b-0ca8e8f90c89/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/a26e0d1d-4886-7d62-6b4f-1996e706463d/fullrender.png"
  },
  {
    "id": "2ef9ee97-4735-e7d9-069f-fb80541468b5",
    "name": "ORA x 颗秒 狂徒",
    "weapon": "vandal",
    "tier": "终极",
    "tierRank": 4,
    "effects": [
      "SoundEffects",
      "Animation",
      "Finisher",
      "SongShuffle"
    ],
    "image": "https://media.valorant-api.com/weaponskins/2ef9ee97-4735-e7d9-069f-fb80541468b5/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/296d373f-4838-5712-d8d4-eaaf5cfabe79/fullrender.png"
  },
  {
    "id": "e5490f71-455b-74ad-f762-f5a876d4dff9",
    "name": "RGX 11z Pro 狂徒",
    "weapon": "vandal",
    "tier": "传奇",
    "tierRank": 3,
    "effects": [
      "VFX",
      "Animation",
      "Finisher",
      "KillCounter"
    ],
    "image": "https://media.valorant-api.com/weaponskins/e5490f71-455b-74ad-f762-f5a876d4dff9/displayicon.png",
    "fullRender": "https://media.valorant-api.com/weaponskinchromas/742740d0-4e50-57e1-af32-f991c7c640f8/fullrender.png"
  }
] as const satisfies readonly Skin[];

export default skinCatalog;
